### ISSUE TITLE
skipsearch LCz_Av_params

### ISSUE THREAD

**Issue by rodrigcd** [fforster/surveysim#2]
There is a problem in [LCz_Av_params](https://github.com/fforster/surveysim/blob/master/lib/LCz_Av_params.py)

if 'scale' is not in self.paramnames (line 267), then skipsearch will not be defined in line 275. Is it enough to add the else statement?

```
if 'scale' in self.paramnames:
    if 'stretch' in self.paramnames:
                if len(self.paramnames) == 2:
                    skipsearch = True
            elif len(self.paramnames) == 1:
                skipsearch = True
else:
    skipsearch = False
```

**Comment by fforster** [comment]
Fixed problem. Skipsearch must be False by default, so it must be set to False before the if...
